### ISSUE TITLE
`Error: InvalidParameterTypeException` for `ompl.request_adapters` with CRX-10iA/L on ROS 2 Humble

### ISSUE THREAD

**Issue by amrokasha76** [paolofrance/ros2_fanuc_interface#16]
## Description
I am using a CRX-10iA/L robot and testing it with ROS 2 Humble on Ubuntu 22.04.5 using mock hardware. However, I am encountering an issue with the `ompl_planner` when launching the move group. The error prevents proper loading of the planner and causes cascading issues, including failure to parse the SRDF, which results in the robot model not loading.

The error message is:
```
[move_group-5] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterTypeException'  
[move_group-5]   what():  parameter 'ompl.request_adapters' has invalid type: expected [string] got [string_array]  
```
## Expected Behavior
By using the command
```
ros2 launch fanuc_control robot_bringup.launch.py use_mock_hardware:=true robot_type:=crx10ia_l
```
The ompl_planner should load without errors, the SRDF should parse successfully, and the robot model should appear in RViz without issues.

## Actual Behavior
- The ompl_planner fails to load due to a `rclcpp::exceptions::InvalidParameterTypeException`
- The SRDF file fails to parse, preventing the robot model from loading.

## Environment
- Robot Model: CRX-10iA/L
- ROS 2 Version: Humble
- OS: Ubuntu 22.04.5
- Planner: OMPL
- Mock Hardware: Enabled

## Log
```
[INFO] [launch]: All log files can be found below /home/okasha/.ros/log/2025-01-24-14-10-43-100465-okasha-74096
[INFO] [launch]: Default logging verbosity is set to INFO
robot_type crx10ia_l
Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.
Using load_yaml() directly is deprecated. Use xacro.load_yaml() instead.
[INFO] [ros2_control_node-1]: process started with pid [74100]
[INFO] [spawner-2]: process started with pid [74102]
[INFO] [spawner-3]: process started with pid [74104]
[INFO] [robot_state_publisher-4]: process started with pid [74106]
[INFO] [move_group-5]: process started with pid [74108]
[INFO] [rviz2-6]: process started with pid [74110]
[ros2_control_node-1] [WARN] [1737717043.466087501] [controller_manager]: [Deprecated] Passing the robot description parameter directly to the control_manager node is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.
[ros2_control_node-1] [INFO] [1737717043.466279516] [resource_manager]: Loading hardware 'crx10ia' 
[ros2_control_node-1] [INFO] [1737717043.466564360] [resource_manager]: Initialize hardware 'crx10ia' 
[ros2_control_node-1] [INFO] [1737717043.466602872] [resource_manager]: Successful initialization of hardware 'crx10ia'
[ros2_control_node-1] [INFO] [1737717043.466630631] [resource_manager]: 'configure' hardware 'crx10ia' 
[ros2_control_node-1] [INFO] [1737717043.466635805] [resource_manager]: Successful 'configure' of hardware 'crx10ia'
[ros2_control_node-1] [INFO] [1737717043.466639686] [resource_manager]: 'activate' hardware 'crx10ia' 
[ros2_control_node-1] [INFO] [1737717043.466642370] [resource_manager]: Successful 'activate' of hardware 'crx10ia'
[ros2_control_node-1] [INFO] [1737717043.468746886] [controller_manager]: update rate is 25 Hz
[ros2_control_node-1] [INFO] [1737717043.468763115] [controller_manager]: Spawning controller_manager RT thread with scheduler priority: 50
[ros2_control_node-1] [WARN] [1737717043.468866106] [controller_manager]: No real-time kernel detected on this system. See [https://control.ros.org/master/doc/ros2_control/controller_manager/doc/userdoc.html] for details on how to enable realtime scheduling.
[robot_state_publisher-4] [WARN] [1737717043.469754198] [kdl_parser]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[robot_state_publisher-4] [INFO] [1737717043.469809865] [robot_state_publisher]: got segment J1_link
[robot_state_publisher-4] [INFO] [1737717043.469840915] [robot_state_publisher]: got segment J2_link
[robot_state_publisher-4] [INFO] [1737717043.469844645] [robot_state_publisher]: got segment J3_link
[robot_state_publisher-4] [INFO] [1737717043.469847242] [robot_state_publisher]: got segment J4_link
[robot_state_publisher-4] [INFO] [1737717043.469849633] [robot_state_publisher]: got segment J5_link
[robot_state_publisher-4] [INFO] [1737717043.469851947] [robot_state_publisher]: got segment J6_link
[robot_state_publisher-4] [INFO] [1737717043.469854331] [robot_state_publisher]: got segment base_link
[robot_state_publisher-4] [INFO] [1737717043.469856851] [robot_state_publisher]: got segment flange
[robot_state_publisher-4] [INFO] [1737717043.469859296] [robot_state_publisher]: got segment flange1
[robot_state_publisher-4] [INFO] [1737717043.469861632] [robot_state_publisher]: got segment tcp
[robot_state_publisher-4] [INFO] [1737717043.469864119] [robot_state_publisher]: got segment tcp_left
[robot_state_publisher-4] [INFO] [1737717043.469866542] [robot_state_publisher]: got segment tcp_right
[robot_state_publisher-4] [INFO] [1737717043.469868964] [robot_state_publisher]: got segment wbase
[move_group-5] [INFO] [1737717043.492546276] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00168361 seconds
[move_group-5] [INFO] [1737717043.492592315] [moveit_robot_model.robot_model]: Loading robot model 'crx10ia_l'...
[move_group-5] [INFO] [1737717043.492598054] [moveit_robot_model.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[move_group-5] [INFO] [1737717043.517713787] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-5] [INFO] [1737717043.517821413] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-5] [INFO] [1737717043.518197791] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-5] [INFO] [1737717043.518369315] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-5] [INFO] [1737717043.518378187] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[move_group-5] [INFO] [1737717043.518479420] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-5] [INFO] [1737717043.518486008] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-5] [INFO] [1737717043.518606875] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
[move_group-5] [INFO] [1737717043.518715204] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-5] [WARN] [1737717043.518951496] [moveit.ros.occupancy_map_monitor.middleware_handle]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[ros2_control_node-1] [INFO] [1737717043.646400387] [controller_manager]: Loading controller 'joint_state_broadcaster'
[move_group-5] [INFO] [1737717043.651989793] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'ompl'
[move_group-5] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterTypeException'
[move_group-5]   what():  parameter 'ompl.request_adapters' has invalid type: expected [string] got [string_array]
[move_group-5] Stack trace (most recent call last):
[move_group-5] #15   Object "", at 0xffffffffffffffff, in 
[move_group-5] #14   Object "/opt/ros/humble/lib/moveit_ros_move_group/move_group", at 0x602d11011724, in 
[ros2_control_node-1] [INFO] [1737717043.670477932] [controller_manager]: Loading controller 'manipulator_controller'
[ros2_control_node-1] [WARN] [1737717043.675630997] [manipulator_controller]: [Deprecated]: "allow_nonzero_velocity_at_trajectory_end" is set to true. The default behavior will change to false.
[rviz2-6] [INFO] [1737717043.676424247] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-6] [INFO] [1737717043.676490289] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[spawner-2] [INFO] [1737717043.679738494] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[rviz2-6] [INFO] [1737717043.689314552] [rviz2]: Stereo is NOT SUPPORTED
[move_group-5] #13   Source "../csu/libc-start.c", line 392, in __libc_start_main_impl [0x72f5dc829e3f]
[move_group-5] #12   Source "../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main [0x72f5dc829d8f]
[move_group-5] #11   Object "/opt/ros/humble/lib/moveit_ros_move_group/move_group", at 0x602d110102c2, in 
[move_group-5] #10   Object "/opt/ros/humble/lib/libmoveit_cpp.so.2.5.7", at 0x72f5dd3f6ff3, in moveit_cpp::MoveItCpp::MoveItCpp(std::shared_ptr<rclcpp::Node> const&, moveit_cpp::MoveItCpp::Options const&)
[move_group-5] #9    Object "/opt/ros/humble/lib/libmoveit_cpp.so.2.5.7", at 0x72f5dd3f3996, in moveit_cpp::MoveItCpp::loadPlanningPipelines(moveit_cpp::MoveItCpp::PlanningPipelineOptions const&)
[move_group-5] #8    Object "/opt/ros/humble/lib/libmoveit_planning_pipeline.so.2.5.7", at 0x72f5dcaff54d, in planning_pipeline::PlanningPipeline::PlanningPipeline(std::shared_ptr<moveit::core::RobotModel const> const&, std::shared_ptr<rclcpp::Node> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[move_group-5] #7    Object "/opt/ros/humble/lib/libmoveit_planning_pipeline.so.2.5.7", at 0x72f5dcafae39, in 
[move_group-5] #6    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x72f5dccae4d7, in __cxa_throw
[move_group-5] #5    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x72f5dccae276, in std::terminate()
[move_group-5] #4    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x72f5dccae20b, in 
[move_group-5] #3    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x72f5dcca2b9d, in 
[move_group-5] #2    Source "./stdlib/abort.c", line 79, in abort [0x72f5dc8287f2]
[move_group-5] #1    Source "../sysdeps/posix/raise.c", line 26, in raise [0x72f5dc842475]
[move_group-5] #0  | Source "./nptl/pthread_kill.c", line 89, in __pthread_kill_internal
[move_group-5]     | Source "./nptl/pthread_kill.c", line 78, in __pthread_kill_implementation
[move_group-5]       Source "./nptl/pthread_kill.c", line 44, in __pthread_kill [0x72f5dc8969fc]
[move_group-5] Aborted (Signal sent by tkill() 74108 1000)
[ros2_control_node-1] [INFO] [1737717043.709291749] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-1] [INFO] [1737717043.709373474] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[spawner-3] [INFO] [1737717043.718896202] [spawner_manipulator_controller]: Loaded manipulator_controller
[ros2_control_node-1] [INFO] [1737717043.749262450] [controller_manager]: Configuring controller 'manipulator_controller'
[ros2_control_node-1] [INFO] [1737717043.749409840] [manipulator_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ros2_control_node-1] [INFO] [1737717043.749424137] [manipulator_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ros2_control_node-1] [INFO] [1737717043.749437472] [manipulator_controller]: Using 'splines' interpolation method.
[ros2_control_node-1] [INFO] [1737717043.750208807] [manipulator_controller]: Controller state will be published at 50.00 Hz.
[ros2_control_node-1] [INFO] [1737717043.750986081] [manipulator_controller]: Action status changes will be monitored at 20.00 Hz.
[rviz2-6] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-6]          at line 253 in /opt/ros/humble/include/class_loader/class_loader/class_loader_core.hpp
[spawner-2] [INFO] [1737717043.870377702] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[spawner-3] [INFO] [1737717043.950553012] [spawner_manipulator_controller]: Configured and activated manipulator_controller
[INFO] [spawner-2]: process has finished cleanly [pid 74102]
[INFO] [spawner-3]: process has finished cleanly [pid 74104]
[ERROR] [move_group-5]: process has died [pid 74108, exit code -6, cmd '/opt/ros/humble/lib/moveit_ros_move_group/move_group --ros-args -p use_sim_time:=False --params-file /tmp/launch_params_y0l4og83 --params-file /tmp/launch_params_v9scmr_q'].
[rviz2-6] [ERROR] [1737717046.775525351] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-6] [INFO] [1737717046.797002864] [moveit_ros_visualization.motion_planning_frame]: MoveGroup namespace changed: / -> . Reloading params.
[rviz2-6] [ERROR] [1737717056.892835865] [rviz]: Could not find parameter robot_description_semantic and did not receive robot_description_semantic via std_msgs::msg::String subscription within 10.000000 seconds.
[rviz2-6] Error:   Could not parse the SRDF XML File. Error=XML_ERROR_EMPTY_DOCUMENT ErrorID=13 (0xd) Line number=0
[rviz2-6]          at line 732 in ./src/model.cpp
[rviz2-6] [ERROR] [1737717056.902383557] [moveit_rdf_loader.rdf_loader]: Unable to parse SRDF
[rviz2-6] [ERROR] [1737717056.920870160] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Robot model not loaded

```

**Comment by paolofrance** [comment]
Hi,
Thank you for this issue.

I replicated the error, and now it should be solved.
I just pushed on branch "paolo" an updated version of the crx10ia_l_moveit_config. 
Please let me know if this solves the problem on your side so that I can close the issue.

paolo

**Comment by amrokasha76** [comment]
Hello,
Thank you for the quick response.

I tested and indeed error above is resolved. RViz now launches with robot models and ompl loads properly. However, motion planning still fails. Sharing the partial log below

```
...
[rviz2-6] [INFO] [1737722621.147166765] [moveit_ros_visualization.motion_planning_frame]: MoveGroup namespace changed: / -> . Reloading params.
[rviz2-6] Warning: Link 'link_1' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 594 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_3' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 594 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_1' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 589 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_1' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 589 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_2' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 589 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_2' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 589 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_3' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 589 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_3' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 589 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_3' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 589 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_4' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 589 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_4' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 589 in ./src/model.cpp
[rviz2-6] Warning: Link 'link_5' is not known to URDF. Cannot disable/enable collisons.
[rviz2-6]          at line 589 in ./src/model.cpp
[rviz2-6] [INFO] [1737722621.233010832] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0398366 seconds
[rviz2-6] [INFO] [1737722621.233040797] [moveit_robot_model.robot_model]: Loading robot model 'crx10ia_l'...
[rviz2-6] [INFO] [1737722621.233048513] [moveit_robot_model.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[rviz2-6] [WARN] [1737722621.240736772] [kdl_parser]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[rviz2-6] [INFO] [1737722621.280775411] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-6] [INFO] [1737722621.281397256] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-6] [INFO] [1737722621.336942757] [interactive_marker_display_99209722634304]: Connected on namespace: /rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic
[rviz2-6] [WARN] [1737722621.339082736] [kdl_parser]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[rviz2-6] [INFO] [1737722621.341951053] [moveit_ros_visualization.motion_planning_frame]: group manipulator
[rviz2-6] [INFO] [1737722621.341964907] [moveit_ros_visualization.motion_planning_frame]: Constructing new MoveGroup connection for group 'manipulator' in namespace ''
[rviz2-6] [INFO] [1737722621.344732964] [interactive_marker_display_99209722634304]: Sending request for interactive markers
[rviz2-6] [INFO] [1737722621.345076775] [move_group_interface]: Ready to take commands for planning group manipulator.
[rviz2-6] [INFO] [1737722621.345628138] [moveit_ros_visualization.motion_planning_frame]: group manipulator
[rviz2-6] [INFO] [1737722621.377911057] [interactive_marker_display_99209722634304]: Service response received for initialization
[rviz2-6] [INFO] [1737722989.375796501] [move_group_interface]: MoveGroup action client/server ready
[move_group-5] [INFO] [1737722989.377120257] [moveit_move_group_default_capabilities.move_action_capability]: Received request
[rviz2-6] [INFO] [1737722989.377442325] [move_group_interface]: Planning request accepted
[move_group-5] [INFO] [1737722989.377490495] [moveit_move_group_default_capabilities.move_action_capability]: executing..
[move_group-5] [INFO] [1737722989.381573542] [moveit_move_group_default_capabilities.move_action_capability]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[move_group-5] [INFO] [1737722989.381610659] [moveit_move_group_capabilities_base.move_group_capability]: Using planning pipeline 'ompl'
[move_group-5] [INFO] [1737722989.382477372] [moveit_collision_detection_fcl.collision_common]: Found a contact between 'J1_link' (type 'Robot link') and 'J2_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[move_group-5] [INFO] [1737722989.382514185] [moveit_collision_detection_fcl.collision_common]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[move_group-5] [INFO] [1737722989.382523978] [moveit_ros.fix_start_state_collision]: Start state appears to be in collision with respect to group manipulator
[move_group-5] [WARN] [1737722989.442644382] [moveit_ros.fix_start_state_collision]: Unable to find a valid state nearby the start state (using jiggle fraction of 0.020000 and 100 sampling attempts). Passing the original planning request to the planner.
[move_group-5] [INFO] [1737722989.443218441] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'manipulator' will use planner 'geometric::RRTstar'. Additional configuration parameters will be set when the planner is constructed.
[move_group-5] [WARN] [1737722989.443877531] [ompl]: ./src/ompl/base/src/Planner.cpp:248 - manipulator/manipulator: Skipping invalid start state (invalid state)
[move_group-5] [ERROR] [1737722989.443904152] [ompl]: ./src/ompl/geometric/planners/rrt/src/RRTstar.cpp:193 - manipulator/manipulator: There are no valid initial states!
[move_group-5] [WARN] [1737722989.443913120] [ompl]: ./src/ompl/base/src/Planner.cpp:248 - manipulator/manipulator: Skipping invalid start state (invalid state)
[move_group-5] [WARN] [1737722989.443938541] [ompl]: ./src/ompl/base/src/Planner.cpp:248 - manipulator/manipulator: Skipping invalid start state (invalid state)
[move_group-5] [WARN] [1737722989.443962005] [ompl]: ./src/ompl/base/src/Planner.cpp:248 - manipulator/manipulator: Skipping invalid start state (invalid state)
[move_group-5] [ERROR] [1737722989.443984086] [ompl]: ./src/ompl/geometric/planners/rrt/src/RRTstar.cpp:193 - manipulator/manipulator: There are no valid initial states!
[move_group-5] [ERROR] [1737722989.443996063] [ompl]: ./src/ompl/geometric/planners/rrt/src/RRTstar.cpp:193 - manipulator/manipulator: There are no valid initial states!
[move_group-5] [ERROR] [1737722989.444042095] [ompl]: ./src/ompl/geometric/planners/rrt/src/RRTstar.cpp:193 - manipulator/manipulator: There are no valid initial states!
[move_group-5] [WARN] [1737722989.444080910] [ompl]: ./src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000590 seconds
[move_group-5] [WARN] [1737722989.444248364] [ompl]: ./src/ompl/base/src/Planner.cpp:248 - manipulator/manipulator: Skipping invalid start state (invalid state)
[move_group-5] [ERROR] [1737722989.444304962] [ompl]: ./src/ompl/geometric/planners/rrt/src/RRTstar.cpp:193 - manipulator/manipulator: There are no valid initial states!
[move_group-5] [WARN] [1737722989.444313459] [ompl]: ./src/ompl/base/src/Planner.cpp:248 - manipulator/manipulator: Skipping invalid start state (invalid state)
[move_group-5] [ERROR] [1737722989.444346123] [ompl]: ./src/ompl/geometric/planners/rrt/src/RRTstar.cpp:193 - manipulator/manipulator: There are no valid initial states!
[move_group-5] [WARN] [1737722989.444375341] [ompl]: ./src/ompl/base/src/Planner.cpp:248 - manipulator/manipulator: Skipping invalid start state (invalid state)
[move_group-5] [WARN] [1737722989.444391278] [ompl]: ./src/ompl/base/src/Planner.cpp:248 - manipulator/manipulator: Skipping invalid start state (invalid state)
[move_group-5] [ERROR] [1737722989.444408633] [ompl]: ./src/ompl/geometric/planners/rrt/src/RRTstar.cpp:193 - manipulator/manipulator: There are no valid initial states!
[move_group-5] [ERROR] [1737722989.444419611] [ompl]: ./src/ompl/geometric/planners/rrt/src/RRTstar.cpp:193 - manipulator/manipulator: There are no valid initial states!
[move_group-5] [WARN] [1737722989.444473634] [ompl]: ./src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000273 seconds
[move_group-5] [WARN] [1737722989.444590286] [ompl]: ./src/ompl/base/src/Planner.cpp:248 - manipulator/manipulator: Skipping invalid start state (invalid state)
[move_group-5] [ERROR] [1737722989.444609366] [ompl]: ./src/ompl/geometric/planners/rrt/src/RRTstar.cpp:193 - manipulator/manipulator: There are no valid initial states!
[move_group-5] [WARN] [1737722989.444630536] [ompl]: ./src/ompl/base/src/Planner.cpp:248 - manipulator/manipulator: Skipping invalid start state (invalid state)
[move_group-5] [ERROR] [1737722989.444649359] [ompl]: ./src/ompl/geometric/planners/rrt/src/RRTstar.cpp:193 - manipulator/manipulator: There are no valid initial states!
[move_group-5] [WARN] [1737722989.444690746] [ompl]: ./src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000139 seconds
[move_group-5] [INFO] [1737722989.445053761] [moveit.ompl_planning.model_based_planning_context]: Unable to solve the planning problem
[move_group-5] [INFO] [1737722989.445096379] [moveit_move_group_default_capabilities.move_action_capability]: Catastrophic failure
[rviz2-6] [INFO] [1737722989.445478137] [move_group_interface]: Planning request aborted
[rviz2-6] [ERROR] [1737722989.446161448] [move_group_interface]: MoveGroupInterface::plan() failed or timeout reached
```

**Comment by paolofrance** [comment]
The problem is that the move_group node detects a collision between J1_link and J2_link, which are names of older versions of the repository.

I see this on the following error:

`[move_group-5] [INFO] [1737722989.382477372] [moveit_collision_detection_fcl.collision_common]: Found a contact between 'J1_link' (type 'Robot link') and 'J2_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.`

Have you tried to clean and build again the workspace?
Try also to update and upgrade the system.

Can you also try with other models, such as crx20ia_l_moveit_config?

paolo

**Comment by amrokasha76** [comment]
I had rebuilt again but I guess something was missing. Performing a clean build solved the issue! Thanks.

I also tested crx20ia_l with mock hardware and had no issues.
